---
- name: Push template to devices in a Site using Cisco DNA Center
  hosts: dnac_host
  connection: local
  gather_facts: no
  vars:
    dnac_conn: &dnac_conn
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"

  tasks:
    # Get the list of devices for the specified site
    - name: Get devices for the specified site
      cisco.dnac.site_membership_info:
        <<: *dnac_conn
        siteId: "{{ dnac_site_id }}"
      register: membership_response

    # Extract device IDs from the membership response
    - name: Extract device IDs
      set_fact:
        device_ids: "{{ membership_response.dnac_response.device[0].response | map(attribute='instanceUuid') | list }}"

    # Push the template to each device
    - name: Push template to devices
      cisco.dnac.configuration_template_deploy:
        <<: *dnac_conn
        templateId: "{{ dnac_template_id }}"
        targetInfo:
          - id: "{{ item }}"
            type: "MANAGED_DEVICE_UUID"
      with_items: "{{ device_ids }}"
